server:
  port: ${PORT:8080}
  servlet:
    context-path: "/api"

spring:
  application:
    name: unigo
  datasource:
    url: mariadb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL}
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:preprod}

jwt:
  secret: ${JWT_SECRET}
  access:
    expires: ${JWT_ACCESS_EXPIRES}
  refresh:
    expires: ${JWT_REFRESH_EXPIRES}
  issuer: ${JWT_ISSUER}

frontend:
  url: ${FRONTEND_URLS}

precioMaximo: ${PRECIO_MAXIMO}